image: golang:1.10

stages:
  - lint
  - test
 
before_script:
  - make dependencies

lint:
  stage: lint
  script: make lint

test:
  stage: test
  script: make cover
  artifacts:
    paths:
      - coverage.out
